# Use postgres/example user/password credentials
version: "3.1"
services:
  db:
    image: postgres
    restart: always
    volumes:
      - database-data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: "unicorn_user"
      POSTGRES_PASSWORD: "magical_password"
      POSTGRES_DB: "cal"
    ports:
      - 5432:5432
  calendso:
    build: .
    restart: always
    ports:
      - 3000:3000
      - 5555:5555
    environment:
      - DOPPLER_TOKEN
    depends_on:
      - db
volumes:
  database-data:
